version: '3.7'

services:
    db:
        image: mysql:latest
        volumes:
            - ./db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: steamer
        ports:
            - '3307:3306'
        networks:
            - server

    # nestjs-app:
    #     image: nest-app3
    #     env_file: environment/.dev.env
    #     restart: always
    #     ports:
    #         - 3000:3000
    #     depends_on:
    #         - db
    #     networks:
    #         - server

networks:
    server:
